proxy_location: EveryNode
http_options:
  host: 0.0.0.0
  port: 8000
grpc_options:
  port: 9000
  grpc_servicer_functions: []
logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true
applications:
- name: llm-serving
  route_prefix: /llm
  import_path: model_pool:app_builder
  args:
    config_file_path: llm_config_default.yaml
    num_gpus: 1
    model_reference_path: model_reference.json
  runtime_env: {}
  deployments:
  - name: ModelController
    num_replicas: 1